[package]
name = "loon-lsp"
version.workspace = true
edition.workspace = true

[dependencies]
loon-lang = { path = "../loon-lang" }
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
dashmap = "6"
ropey = "1"
serde_json = "1"
